// Code generated by protoc-gen-go.
// source: command_line.proto
// DO NOT EDIT!

/*
Package command_line is a generated protocol buffer package.

It is generated from these files:
	command_line.proto

It has these top-level messages:
	CommandRequest
	CommandResponse
*/
package command_line

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandRequest struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *CommandRequest) Reset()                    { *m = CommandRequest{} }
func (m *CommandRequest) String() string            { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()               {}
func (*CommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommandRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type CommandResponse struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *CommandResponse) Reset()                    { *m = CommandResponse{} }
func (m *CommandResponse) String() string            { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()               {}
func (*CommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommandResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*CommandRequest)(nil), "command_line.CommandRequest")
	proto.RegisterType((*CommandResponse)(nil), "command_line.CommandResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CommandLine service

type CommandLineClient interface {
	Echo(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
}

type commandLineClient struct {
	cc *grpc.ClientConn
}

func NewCommandLineClient(cc *grpc.ClientConn) CommandLineClient {
	return &commandLineClient{cc}
}

func (c *commandLineClient) Echo(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := grpc.Invoke(ctx, "/command_line.CommandLine/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CommandLine service

type CommandLineServer interface {
	Echo(context.Context, *CommandRequest) (*CommandResponse, error)
}

func RegisterCommandLineServer(s *grpc.Server, srv CommandLineServer) {
	s.RegisterService(&_CommandLine_serviceDesc, srv)
}

func _CommandLine_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandLineServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/command_line.CommandLine/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandLineServer).Echo(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommandLine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "command_line.CommandLine",
	HandlerType: (*CommandLineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _CommandLine_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "command_line.proto",
}

func init() { proto.RegisterFile("command_line.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0x89, 0xcf, 0xc9, 0xcc, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x41, 0x16, 0x53, 0x52, 0xe1, 0xe2, 0x73, 0x86, 0xf0, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0x84, 0xb8, 0x58, 0x4a, 0x52, 0x2b, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0,
	0x6c, 0x25, 0x55, 0x2e, 0x7e, 0xb8, 0xaa, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x6c, 0xca, 0x8c,
	0x42, 0xb8, 0xb8, 0xa1, 0xca, 0x7c, 0x32, 0xf3, 0x52, 0x85, 0x5c, 0xb9, 0x58, 0x5c, 0x93, 0x33,
	0xf2, 0x85, 0x64, 0xf4, 0x50, 0x9c, 0x81, 0x6a, 0x9f, 0x94, 0x2c, 0x0e, 0x59, 0x88, 0x3d, 0x4a,
	0x0c, 0x49, 0x6c, 0x60, 0x77, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x13, 0x91, 0x1d, 0xb4,
	0xcd, 0x00, 0x00, 0x00,
}
